/*
 * tools/archive-sync.js — season backfill + 6-hourly cron for the NHC text
 * archive (Track C M1). Fetches every TWDAT/TWOAT/TWDEP/TWOEP issuance into
 * archive/{year}/{basin}/ and re-derives the compact per-basin summaries under
 * archive/derived/.
 *
 * Usage:  node tools/archive-sync.js [--since YYYY-MM-DD] [--derive]
 *   --since   only fetch issuances stamped on/after this UTC day
 *             (default 2026-06-01, the SEASON_START constant)
 *   --derive  after syncing, re-read ALL raw files and rewrite
 *             archive/derived/{year}-AT.json + {year}-EP.json
 *
 * Layout:  TWDAT,TWOAT -> archive/{year}/AT/ ; TWDEP,TWOEP -> archive/{year}/EP/
 *          filename kept verbatim (TWDAT.202607141800.txt).
 *
 * Dev-only and NETWORK-DEPENDENT (Node 18+ global fetch, zero deps). Polite:
 * one listing request per type, ~150 ms between product fetches, sequential.
 * IDEMPOTENT: files already on disk are skipped, so re-runs only fetch new
 * issuances — that is what lets the cron commit "only if changed". A per-product
 * fetch error is logged and skipped (never a partial/fabricated file); a listing
 * that is unreachable sets a non-zero exit so the cron run shows red.
 *
 * Cron: .github/workflows/archive.yml runs `--derive` every 6 hours and commits
 * archive/ to main. Raw .txt is GROUND TRUTH (committed); derived JSON is
 * REGENERATED by --derive, never hand-edited. --derive output is deterministic
 * (records sorted by stamp, ties by filename, no generated-at timestamp), so a
 * re-derive with no new data produces a zero diff.
 *
 * The pure helpers (basinForType/kindForType/sinceBound/filterSince/deriveRecord/
 * parseArgs) are exported for test.js, which stays offline; only sync() touches
 * the network. Never runs in the browser.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const P = require('../parser.js');
const { BASE, UA, listingNames, stampOf } = require('./nhc-text-archive.js');
const { summarizeTWD, summarizeTWO } = require('./derive-summary.js');

const SEASON_START = '2026-06-01';
const SEASON = Number(SEASON_START.slice(0, 4)); // 2026
const ARCHIVE = path.join(__dirname, '..', 'archive');
const FETCH_DELAY_MS = 150;

// The four products this archive tracks, each with its basin (directory) and
// kind (parser path). Central Pacific is out of scope, matching the app.
const TYPES = [
  { type: 'TWDAT', basin: 'AT', kind: 'TWD' },
  { type: 'TWOAT', basin: 'AT', kind: 'TWO' },
  { type: 'TWDEP', basin: 'EP', kind: 'TWD' },
  { type: 'TWOEP', basin: 'EP', kind: 'TWO' },
];

// --- pure helpers (exported for offline tests) ----------------------------------

// Product type -> basin directory / parser kind. Derived from the id itself so
// a new product string can't silently miss the mapping table.
function basinForType(type) {
  if (/AT$/.test(type)) return 'AT';
  if (/EP$/.test(type)) return 'EP';
  return null;
}
function kindForType(type) {
  if (/^TWD/.test(type)) return 'TWD';
  if (/^TWO/.test(type)) return 'TWO';
  return null;
}

// '--since YYYY-MM-DD' -> inclusive 12-digit lower-bound stamp (00:00Z that day),
// or null when malformed. Stamps are fixed-width numeric strings, so a lexical
// compare against this bound is a correct chronological compare.
function sinceBound(sinceISO) {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(sinceISO || ''));
  return m ? m[1] + m[2] + m[3] + '0000' : null;
}

// Keep only listing names whose stamp is on/after --since.
function filterSince(names, sinceISO) {
  const bound = sinceBound(sinceISO);
  if (!bound) return names.slice();
  return names.filter(function (n) {
    const s = stampOf(n);
    return s && s >= bound;
  });
}

// One raw file's text -> its derived record, wrapping the parse so a single
// never-seen product can't kill the whole --derive run: on error the record is
// an honest {file, kind, stamp, error} placeholder (future fixture material).
function deriveRecord(file, kind, basin, text) {
  const stamp = stampOf(file);
  try {
    if (kind === 'TWO') return summarizeTWO(P.parseTWO(text, { basin: basin }), { file: file, kind: kind, stamp: stamp });
    return summarizeTWD(P.parse(text, { basin: basin }), { file: file, kind: kind, stamp: stamp });
  } catch (e) {
    return { file: file, kind: kind, stamp: stamp, error: (e && e.message) ? e.message : String(e) };
  }
}

// Argv (after the node/script args) -> { since, derive }.
function parseArgs(argv) {
  const args = { since: SEASON_START, derive: false };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--derive') args.derive = true;
    else if (argv[i] === '--since') args.since = argv[++i];
    else if (argv[i].indexOf('--since=') === 0) args.since = argv[i].slice('--since='.length);
  }
  return args;
}

// --- network sync (not exercised by test.js) ------------------------------------

const sleep = function (ms) { return new Promise(function (r) { setTimeout(r, ms); }); };

async function fetchText(url) {
  const res = await fetch(url, UA);
  if (!res.ok) throw new Error('HTTP ' + res.status + ' for ' + url);
  return res.text();
}

// Fetch one type's new issuances. Returns false (already logged) if the year's
// directory listing itself is unreachable, so the caller can exit non-zero.
async function syncType(t, sinceISO) {
  const yearPath = 'text/' + t.type + '/' + SEASON + '/';
  let listing;
  try {
    listing = await fetchText(BASE + yearPath);
  } catch (e) {
    console.error(t.type + ': listing fetch failed — ' + (e.message || e));
    return false;
  }
  const names = filterSince(listingNames(listing, t.type), sinceISO);
  const dir = path.join(ARCHIVE, String(SEASON), t.basin);
  fs.mkdirSync(dir, { recursive: true });
  let fetched = 0, skipped = 0, failed = 0;
  for (const name of names) {
    const dest = path.join(dir, name);
    if (fs.existsSync(dest)) { skipped++; continue; } // idempotent
    try {
      const raw = await fetchText(BASE + yearPath + name);
      fs.writeFileSync(dest, raw.replace(/\r\n?/g, '\n')); // LF, matching .gitattributes
      fetched++;
    } catch (e) {
      // skip-and-log: a failed product never becomes a partial or invented file
      console.error('  ' + name + ': fetch failed — ' + (e.message || e));
      failed++;
    }
    await sleep(FETCH_DELAY_MS);
  }
  console.log(t.type + ': ' + names.length + ' since ' + sinceISO + ' — ' +
    fetched + ' new, ' + skipped + ' on disk, ' + failed + ' failed');
  return true;
}

async function sync(sinceISO) {
  let allListingsOk = true;
  for (const t of TYPES) {
    const ok = await syncType(t, sinceISO);
    if (!ok) allListingsOk = false;
  }
  if (!allListingsOk) process.exitCode = 1; // an unreachable listing shows the run red
}

// --- derive (offline: reads committed raw text) ---------------------------------

// Read every raw product in a basin, sorted deterministically (stamp asc, ties
// by filename), and build its derived record.
function deriveBasin(basin) {
  const dir = path.join(ARCHIVE, String(SEASON), basin);
  let files = [];
  if (fs.existsSync(dir)) {
    files = fs.readdirSync(dir).filter(function (f) { return /^TW[DO](?:AT|EP)\.\d{12}\.txt$/.test(f); });
  }
  files.sort(function (a, b) {
    const sa = stampOf(a) || '', sb = stampOf(b) || '';
    if (sa !== sb) return sa < sb ? -1 : 1;
    return a < b ? -1 : (a > b ? 1 : 0);
  });
  return files.map(function (f) {
    const kind = kindForType(f.slice(0, 5));
    const text = fs.readFileSync(path.join(dir, f), 'utf8');
    return deriveRecord(f, kind, basin, text);
  });
}

function derive() {
  const derivedDir = path.join(ARCHIVE, 'derived');
  fs.mkdirSync(derivedDir, { recursive: true });
  for (const basin of ['AT', 'EP']) {
    const products = deriveBasin(basin);
    const out = {
      _readme: 'Derived per-basin summaries of the committed NHC text archive ' +
        '(archive/' + SEASON + '/' + basin + '/). Regenerated by ' +
        '`node tools/archive-sync.js --derive` — NEVER hand-edit. The raw .txt files ' +
        'are ground truth; this is a compact, re-derivable projection ' +
        '(shape: tools/derive-summary.js, checked by node test.js).',
      season: SEASON,
      basin: basin,
      products: products,
    };
    const file = path.join(derivedDir, SEASON + '-' + basin + '.json');
    fs.writeFileSync(file, JSON.stringify(out, null, 2) + '\n');
    console.log('derived ' + SEASON + '-' + basin + '.json — ' + products.length + ' products');
  }
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  await sync(args.since);
  if (args.derive) derive();
}

module.exports = {
  SEASON, SEASON_START, TYPES,
  basinForType, kindForType, sinceBound, filterSince, deriveRecord, parseArgs,
};

if (require.main === module) {
  main().catch(function (e) { console.error(e.message || e); process.exit(1); });
}
