/*
 * tools/build-lineage.js — season lineage engine (Track C M2). Composes
 * diff.js's adjacent-issuance pairing across the WHOLE committed archive into
 * entity chains — waves, invests, cyclones — plus the conservative genesis
 * links between them, written to archive/derived/lineage-2026.json.
 *
 * Usage:  node tools/build-lineage.js   (no args; SEASON is a constant)
 *   Reads archive/2026/{AT,EP}/TW*.txt, FULL-parses each with parser.js
 *   (P.parse for TWD*, P.parseTWO for TWO*, explicit {basin} so diff.js gets
 *   the exact shapes it was built for), sorts each basin into a TWD stream and
 *   a TWO stream by stamp (ties by filename), and composes chains.
 *
 * THE CREDIBILITY RULE IS ABSOLUTE: prefer broken chains over invented links.
 * A wrong lineage is this feature's "Tropical Depression Or". Every gate errs
 * toward breaking; ambiguity produces NO link; nothing upgrades confidence.
 *
 * Composition gates (on top of diff.js, which is NOT modified — a shell file):
 *   1. time-gap guard: consecutive products > MAX_GAP_H apart -> close ALL open
 *      chains at the gap; never pair across it.
 *   2. wave drift sanity: reject a diff.js wave pair whose mean-lon moves
 *      > EAST_JITTER_DEG eastward (waves drift west; small eastward = re-analysis).
 *      Rejection breaks the old chain and opens a new one — never a re-match.
 *   3. invest identity: a chain's tag is its first tagged sighting; diff.js
 *      forbids cross-tag and null-position proximity pairs, and this layer also
 *      refuses a pair that would drag a SECOND distinct tag into a chain (an
 *      untagged bridge can't silently merge AL90 with AL91).
 *   4. cyclones: name identity from diffTWD, same gap guard; classification
 *      transitions (TD->TS->H->post-trop) are normal within a chain.
 * Genesis links are drawn only after the chains exist, under tight distance/time
 * gates, and any ambiguity kills the link.
 *
 * Output is DETERMINISTIC: every array sorted, no generated-at timestamp, so a
 * rebuild over an unchanged archive is byte-identical (the fixtures/derived
 * discipline — regenerated by tooling, never hand-edited).
 *
 * The pure composition pieces (chainWaves/chainInvests/chainCyclones,
 * composeChains, linkGenesis, gapExceeded/waveDriftReject, the gate constants)
 * are exported for test.js, which stays offline and drives them with synthetic
 * parse-shaped objects. Only the CLI body (require.main) touches the filesystem.
 * Zero dependencies; never runs in the browser.
 *
 * Internal product-record shape (what the stream arrays hold, and what synthetic
 * tests construct):  { stamp: '202606010425', file: 'TWDAT.202606010425.txt',
 *   parsed: <full P.parse()/P.parseTWO() result> }.  parsed.waves/.cyclones for
 *   a TWD, parsed.disturbances for a TWO — exactly diff.js's inputs.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const P = require('../parser.js');
const HCDiff = require('../diff.js');
const { stampOf, stampDate } = require('./nhc-text-archive.js');

const SEASON = 2026;
const ARCHIVE = path.join(__dirname, '..', 'archive');
const RAW_RE = /^TW[DO](?:AT|EP)\.\d{12}\.txt$/;

// --- composition gate constants -------------------------------------------------
const MAX_GAP_H = 18;        // > this between consecutive products -> close all chains
const EAST_JITTER_DEG = 2;   // wave mean-lon may drift east this far (re-analysis) before it's a new wave
// genesis gates (all conservative — ambiguity always wins by killing the link)
const GENESIS_WAVE_HOURS = 24; // wave sighting within +/- this of the invest's first sighting
const GENESIS_WAVE_LON = 4;    // |wave meanLon - invest lon| ceiling
const GENESIS_LAT_PAD = 3;     // wave axis lat-span padded this far must contain invest lat
const GENESIS_AMBIG_DEG = 2;   // two candidate waves this close in lon-distance -> ambiguous -> no link
const GENESIS_CYC_HOURS = 36;  // cyclone first sighting within this of the invest's last mappable sighting
const GENESIS_CYC_DIST = 3;    // flat-degree distance ceiling for invest -> cyclone

// --- small helpers --------------------------------------------------------------

// Hours between two 12-digit stamps (cur - prev), or null if either is unreadable.
function hoursBetween(prevStamp, curStamp) {
  const a = stampDate(prevStamp), b = stampDate(curStamp);
  if (!a || !b) return null;
  return (b.getTime() - a.getTime()) / 3600e3;
}

// gate 1: consecutive products too far apart in time to pair (or an unreadable
// stamp — a gap we can't measure is a gap we don't cross). Broken > bridged.
function gapExceeded(prevStamp, curStamp) {
  const h = hoursBetween(prevStamp, curStamp);
  return h == null || h > MAX_GAP_H;
}

// gate 2: reject a wave pair that moves too far EAST. Waves drift west; a large
// eastward jump is a different wave the proximity gate happened to catch.
function waveDriftReject(prevAxis, curAxis) {
  return (HCDiff.meanLon(curAxis) - HCDiff.meanLon(prevAxis)) > EAST_JITTER_DEG;
}

function round3(x) { return Math.round(x * 1000) / 1000; }

// --- generic chain composition --------------------------------------------------
//
// composeChains walks a stamp-sorted product stream, extends open chains through
// diff.js pairs that survive the family's gate, and opens a fresh chain for every
// feature that didn't pair (added, gate-rejected, or across a time gap). One-to-
// one pairing (diff.js) means each open chain gains at most one sighting per step.
//
// opts: { basin, letter, extract, diffPairs, gate, makeSighting, newChain,
//         onSighting?, sigOf } — see the three family builders below.
function composeChains(products, opts) {
  const chains = [];
  function openNew(product, feature) {
    const chain = opts.newChain(feature);
    chain.sightings = chain.sightings || [];
    chain.sightings.push(opts.makeSighting(product, feature, null));
    if (opts.onSighting) opts.onSighting(chain, feature);
    chains.push(chain);
    return chain;
  }
  let open = new Map(); // feature-object (in the LAST product) -> its open chain
  for (let i = 0; i < products.length; i++) {
    const cur = products[i];
    const feats = opts.extract(cur.parsed);
    // First product, or a time gap: no pairing — every current feature opens a
    // new chain and the old open set is abandoned (its chains stay as they are).
    if (i === 0 || gapExceeded(products[i - 1].stamp, cur.stamp)) {
      const next = new Map();
      for (const f of feats) next.set(f, openNew(cur, f));
      open = next;
      continue;
    }
    const pairs = opts.diffPairs(products[i - 1].parsed, cur.parsed);
    const next = new Map();
    const paired = new Set();
    for (const pr of pairs) {
      const chain = open.get(pr.prev);
      if (!chain) continue; // prev not in an open chain (shouldn't happen) — leave cur for a new chain
      const link = opts.gate(pr, chain);
      if (link == null) continue; // gate rejected the pair -> break; cur opens a new chain below
      chain.sightings.push(opts.makeSighting(cur, pr.cur, link));
      if (opts.onSighting) opts.onSighting(chain, pr.cur);
      next.set(pr.cur, chain);
      paired.add(pr.cur);
    }
    for (const f of feats) {
      if (!paired.has(f)) next.set(f, openNew(cur, f));
    }
    open = next;
  }
  return assignIds(chains, opts.basin, opts.letter, opts.sigOf);
}

// Deterministic ids: sort chains by first stamp then a family signature, then n
// disambiguates chains sharing a first stamp (1-based within that stamp group).
// The result is already in the output order (first stamp, then id).
function assignIds(chains, basin, letter, sigOf) {
  chains.sort(function (a, b) {
    const fa = a.sightings[0].stamp, fb = b.sightings[0].stamp;
    if (fa !== fb) return fa < fb ? -1 : 1;
    const sa = sigOf(a), sb = sigOf(b);
    return sa < sb ? -1 : (sa > sb ? 1 : 0);
  });
  let i = 0;
  while (i < chains.length) {
    const fs0 = chains[i].sightings[0].stamp;
    let n = 1, j = i;
    while (j < chains.length && chains[j].sightings[0].stamp === fs0) {
      chains[j].id = basin + '-' + letter + '-' + fs0 + '-' + n;
      j++; n++;
    }
    i = j;
  }
  return chains;
}

// --- the three families ---------------------------------------------------------

function chainWaves(products, basin) {
  return composeChains(products, {
    basin: basin, letter: 'W',
    extract: function (p) { return p.waves || []; },
    diffPairs: function (a, b) { return HCDiff.diffProducts(a, b, 'TWD').waves.pairs; },
    gate: function (pr) { return waveDriftReject(pr.prev.axis, pr.cur.axis) ? null : 'axis'; },
    newChain: function () { return { id: null, sightings: [] }; },
    makeSighting: function (prod, f, link) {
      return {
        stamp: prod.stamp, file: prod.file,
        meanLon: round3(HCDiff.meanLon(f.axis)),
        axis: (f.axis || []).map(function (pt) { return { lat: pt.lat, lon: pt.lon }; }),
        inferred: !!f.inferred,
        link: link,
      };
    },
    sigOf: function (c) { return String(c.sightings[0].meanLon); },
  });
}

function chainInvests(products, basin) {
  return composeChains(products, {
    basin: basin, letter: 'I',
    extract: function (p) { return p.disturbances || []; },
    diffPairs: function (a, b) { return HCDiff.diffProducts(a, b, 'TWO').disturbances.pairs; },
    // 'tag' when both sides carry the same invest tag, else 'proximity'; refuse a
    // pair that would pull a DIFFERENT tag into an already-tagged chain.
    gate: function (pr, chain) {
      const curTag = pr.cur.invest || null;
      if (curTag && chain.tag && curTag !== chain.tag) return null;
      return (pr.prev.invest && pr.cur.invest && pr.prev.invest === pr.cur.invest) ? 'tag' : 'proximity';
    },
    newChain: function () { return { id: null, tag: null, sightings: [] }; },
    onSighting: function (chain, f) { if (!chain.tag && f.invest) chain.tag = f.invest; },
    makeSighting: function (prod, f, link) {
      return {
        stamp: prod.stamp, file: prod.file,
        lat: f.lat, lon: f.lon,
        chance48: f.chance48 || null, chance7: f.chance7 || null,
        tagged: !!f.invest,
        link: link,
      };
    },
    sigOf: function (c) { return JSON.stringify([c.tag || '', c.sightings[0].lat, c.sightings[0].lon]); },
  });
}

function chainCyclones(products, basin) {
  return composeChains(products, {
    basin: basin, letter: 'C',
    extract: function (p) { return p.cyclones || []; },
    diffPairs: function (a, b) { return HCDiff.diffProducts(a, b, 'TWD').cyclones.pairs; },
    gate: function () { return 'name'; }, // name identity is diff.js's job; gap guard applies in composeChains
    newChain: function (f) { return { id: null, name: f.name, sightings: [] }; },
    makeSighting: function (prod, f, link) {
      return {
        stamp: prod.stamp, file: prod.file,
        lat: f.lat, lon: f.lon,
        classification: f.classification || null,
        windKt: f.windKt == null ? null : f.windKt,
        link: link,
      };
    },
    sigOf: function (c) { return String(c.name); },
  });
}

// --- genesis links (chain-to-chain, conservative) -------------------------------

function linkGenesis(basin, coll) {
  const links = [];

  // wave -> invest: at the invest chain's FIRST (mappable) sighting, the wave
  // chains whose axis passes near it in space and time. Two comparably-close
  // candidates -> ambiguous -> no link.
  for (const inv of coll.invests) {
    const first = inv.sightings[0];
    if (first.lat == null || first.lon == null) continue;
    const invT = stampDate(first.stamp);
    if (!invT) continue;
    const cands = [];
    for (const w of coll.waves) {
      let best = null;
      for (const s of w.sightings) {
        const wt = stampDate(s.stamp);
        if (!wt || Math.abs(wt.getTime() - invT.getTime()) > GENESIS_WAVE_HOURS * 3600e3) continue;
        const dLon = Math.abs(s.meanLon - first.lon);
        if (dLon > GENESIS_WAVE_LON) continue;
        const lats = s.axis.map(function (p) { return p.lat; });
        const lo = Math.min.apply(null, lats) - GENESIS_LAT_PAD;
        const hi = Math.max.apply(null, lats) + GENESIS_LAT_PAD;
        if (first.lat < lo || first.lat > hi) continue;
        if (best == null || dLon < best) best = dLon;
      }
      if (best != null) cands.push({ id: w.id, dist: best });
    }
    if (!cands.length) continue;
    cands.sort(function (a, b) { return a.dist - b.dist || (a.id < b.id ? -1 : 1); });
    if (cands.length >= 2 && (cands[1].dist - cands[0].dist) <= GENESIS_AMBIG_DEG) continue; // ambiguous
    links.push({ kind: 'wave-invest', from: cands[0].id, to: inv.id, atStamp: first.stamp, confidence: 'inferred-genesis' });
  }

  // invest -> cyclone: a cyclone's FIRST sighting near an invest chain's LAST
  // mappable sighting in space and time. Two qualifying invests -> ambiguous.
  for (const cyc of coll.cyclones) {
    const first = cyc.sightings[0];
    if (first.lat == null || first.lon == null) continue;
    const cycT = stampDate(first.stamp);
    if (!cycT) continue;
    const quals = [];
    for (const inv of coll.invests) {
      let last = null;
      for (const s of inv.sightings) if (s.lat != null && s.lon != null) last = s;
      if (!last) continue;
      const lt = stampDate(last.stamp);
      if (!lt || Math.abs(cycT.getTime() - lt.getTime()) > GENESIS_CYC_HOURS * 3600e3) continue;
      const d = Math.sqrt(Math.pow(first.lat - last.lat, 2) + Math.pow(first.lon - last.lon, 2));
      if (d > GENESIS_CYC_DIST) continue;
      quals.push({ id: inv.id, dist: d });
    }
    if (quals.length !== 1) continue; // 0 = nothing; >=2 = ambiguous -> no link
    links.push({ kind: 'invest-cyclone', from: quals[0].id, to: cyc.id, atStamp: first.stamp, confidence: 'inferred-genesis' });
  }

  links.sort(function (a, b) {
    if (a.atStamp !== b.atStamp) return a.atStamp < b.atStamp ? -1 : 1;
    if (a.kind !== b.kind) return a.kind < b.kind ? -1 : 1;
    if (a.from !== b.from) return a.from < b.from ? -1 : 1;
    return a.to < b.to ? -1 : (a.to > b.to ? 1 : 0);
  });
  return links;
}

// --- filesystem (CLI only; not exercised by test.js) ----------------------------

// Read one basin's raw archive into two stamp-sorted streams (TWD, TWO). A file
// that fails to parse is logged and skipped — never fabricated into a chain.
function readStreams(basin) {
  const dir = path.join(ARCHIVE, String(SEASON), basin);
  const twd = [], two = [];
  let files = [];
  if (fs.existsSync(dir)) files = fs.readdirSync(dir).filter(function (f) { return RAW_RE.test(f); });
  files.sort(function (a, b) {
    const sa = stampOf(a) || '', sb = stampOf(b) || '';
    if (sa !== sb) return sa < sb ? -1 : 1;
    return a < b ? -1 : (a > b ? 1 : 0);
  });
  for (const f of files) {
    const kind = /^TWD/.test(f) ? 'TWD' : 'TWO';
    const text = fs.readFileSync(path.join(dir, f), 'utf8');
    let parsed;
    try {
      parsed = kind === 'TWO' ? P.parseTWO(text, { basin: basin }) : P.parse(text, { basin: basin });
    } catch (e) {
      console.error('  parse failed, skipping ' + f + ' — ' + (e && e.message ? e.message : e));
      continue;
    }
    (kind === 'TWO' ? two : twd).push({ stamp: stampOf(f), file: f, parsed: parsed });
  }
  return { twd: twd, two: two };
}

function buildBasin(basin) {
  const s = readStreams(basin);
  const waves = chainWaves(s.twd, basin);
  const cyclones = chainCyclones(s.twd, basin);
  const invests = chainInvests(s.two, basin);
  const genesis = linkGenesis(basin, { waves: waves, invests: invests, cyclones: cyclones });
  console.log(basin + ': ' + s.twd.length + ' TWD + ' + s.two.length + ' TWO -> ' +
    waves.length + ' wave, ' + invests.length + ' invest, ' + cyclones.length + ' cyclone chains, ' +
    genesis.length + ' genesis link(s)');
  return { waves: waves, invests: invests, cyclones: cyclones, genesis: genesis };
}

function build() {
  const out = {
    _readme: 'Season lineage: wave/invest/cyclone chains + genesis links composed ' +
      'from the committed NHC text archive (archive/' + SEASON + '/{AT,EP}/) by ' +
      '`node tools/build-lineage.js` — NEVER hand-edit. Deterministic and re-derivable; ' +
      'the credibility rule is absolute — prefer broken chains over invented links.',
    season: SEASON,
    basins: {},
  };
  for (const basin of ['AT', 'EP']) out.basins[basin] = buildBasin(basin);
  const derivedDir = path.join(ARCHIVE, 'derived');
  fs.mkdirSync(derivedDir, { recursive: true });
  const file = path.join(derivedDir, 'lineage-' + SEASON + '.json');
  fs.writeFileSync(file, JSON.stringify(out, null, 2) + '\n');
  console.log('wrote lineage-' + SEASON + '.json');
}

module.exports = {
  SEASON,
  MAX_GAP_H, EAST_JITTER_DEG,
  GENESIS_WAVE_HOURS, GENESIS_WAVE_LON, GENESIS_LAT_PAD, GENESIS_AMBIG_DEG,
  GENESIS_CYC_HOURS, GENESIS_CYC_DIST,
  hoursBetween, gapExceeded, waveDriftReject,
  composeChains, chainWaves, chainInvests, chainCyclones, linkGenesis,
};

if (require.main === module) build();
